---
title: "Study 1 Models"
subtitle: Vis 2022 Posteriors
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load models

```{r}
library(brms)
library(sjPlot)
library(brmstools)

df <- readr::read_csv("../data/belief_data_prolific_all_exclude.csv")

# refactor and categorize
df$vis_condition <- factor(df$vis_condition, c("uncertainty","scatter","hop"))
levels(df$vis_condition ) <- c("scatter","uncertainty","hop")
```

```{r}
library(sjPlot)
library(ggplot2)
```


## Absolute Belief Models

```{r}
load("../models/fit_baseline_abs_belief2.rda")
load("../models/fit_baseline_abs_belief5.rda")
load("../models/fit_baseline_abs_belief6.rda")
```

### Baseline

```{r}
bm2
```

```{r}
tab_model(bm2)
```

### BM5

```{r}
bm5
```

```{r}
tab_model(bm5)
```

### BM6

```{r}
bm6
```

```{r}
tab_model(bm6)
```

```{r}
pInter1 <- plot_model(bm6, type = "pred", terms = c("pre_attitude_strength","vis_condition")) +
  labs(title = " ",
       x = "Pre Attitude Strength",
       y = "Absolute Belief Difference")  +
  scale_color_discrete(name = "Vis Condition", labels = c("Scatter","Cone","HOPs"))
```

```{r}
pCond1 <- coefplot(bm6, pars = c("vis_conditionuncertainty","vis_conditionhop")) +
  scale_y_discrete(labels = c("vis_conditionuncertainty" = "Cone","vis_conditionhop" = "HOPs")) +
  labs(x = "Absolute belief change", y = "") +
  xlim(-.6,.6) +
  geom_vline(xintercept = 0)
```


## Uncertainty Difference Models

```{r}
load("../models/fit_baseline_diff_uncertainty2.rda")
load("../models/fit_baseline_diff_uncertainty5.rda")
load("../models/fit_baseline_diff_uncertainty6.rda")
```

### Baseline

```{r}
bm2
```

```{r}
tab_model(bm2)
```

### BM5

```{r}
bm5
```

```{r}
tab_model(bm5)
```

### BM6

```{r}
bm6
```

```{r}
tab_model(bm6)
```

```{r}
pInter2 <- plot_model(bm6, type = "pred", terms = c("pre_attitude_strength","vis_condition")) +
  labs(title = " ",
       x = "Pre Attitude Strength",
       y = "Uncertainty Difference") +
  scale_color_discrete(name = "Vis Condition", labels = c("Scatter","Cone","HOPs"))
```

```{r}
pCond2 <- coefplot(bm6, pars = c("vis_conditionuncertainty","vis_conditionhop")) +
  scale_y_discrete(labels = c("vis_conditionuncertainty" = "Cone","vis_conditionhop" = "HOPs")) +
  labs(x = "Uncertainty difference", y = "") +
  xlim(-.1,.1) +
  geom_vline(xintercept = 0)
```


```{r}
library(patchwork)

(pInter1 + pInter2) + plot_layout(guides = "collect")

ggsave("../img/posterior-attitude.pdf", width = 8, height = 4)
```

```{r}
(pCond1 + pCond2) + plot_layout(guides = "collect")

ggsave("../img/me-uncertainty.pdf", width = 8, height = 2)
```

